default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: tasks
  pool: 5
  timeout: 5000
  username: user1
  password: 1234

test:
  adapter: postgresql
  encoding: unicode
  database: tasks
  pool: 5
  timeout: 5000
  username: user1
  password: 1234
